#ifndef DOUBLE_PENDULUM_CONSTANTS_H
#define DOUBLE_PENDULUM_CONSTANTS_H

#define WINDOW_WIDTH 1000
#define WINDOW_HEIGHT 700
#define TARGET_FPS 60

#define FONT_SIZE_TITLE 34
#define FONT_SIZE_MENU 21
#define FONT_SIZE_FOOTER 13

#define UI_TITLE_Y_RATIO 0.2f
#define UI_MENU_X_RATIO 0.35f
#define UI_FOOTER_Y_RATIO 0.85f


#define GOLDEN_RATIO 1.6180339887f

#define BASE_LENGTH 150.0f
#define BASE_MASS 9.0f
#define TRAIL_MAX_LENGTH 200
#define ARM_THICKNESS 9

#define PIXELS_PER_METER 150.0f // same as base_length
#define GRAVITY (9.81f * PIXELS_PER_METER)


#endif //DOUBLE_PENDULUM_CONSTANTS_H
